replaced most uses of FuseProject rule to use empty default constructor
jbosstools/jbosstools-fuse pull request #1649
Opened 2021-02-02 11:01 UTC by lhein

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

2021-02-02 14:21 UTC, bfitzpat approved these changes
Definitely cleans things up a bit and makes them simpler. Why are we shifting to the default empty constructor instead of passing the simple class name as a project name for the FuseProject now?

2021-02-02 14:42 UTC, apupier commented
> Why are we shifting to the default empty constructor instead of passing the simple class name as a project name for the FuseProject now?

https://github.com/jbosstools/jbosstools-fuse/pull/1648#issue-563899430

while moving to new Ci Lars is hitting flakier tests. Wiht error mentioning that the previous project already exists. SO sound slike, the clean is not always working on time. Using different name allows to avoid this kind of issue. it is also cleaner to have a specific name for each test instead of the whole class.

2021-02-10 08:26 UTC, apupier commented on core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/test/util/editor/AbstractCamelEditorIT.java
> +		fuseProject = new FuseProject();
this one cannot use the no-arg constructor because it is not used as a JUnit Rule.

2021-02-10 08:28 UTC, apupier requested changes
- oen test failing, see comment https://github.com/jbosstools/jbosstools-fuse/pull/1649/files#r573531073
- please add issue jira number in comment
- please add the reason to use the no-arg constructor in the commit message

2021-02-12 11:56 UTC, apupier approved these changes

2021-02-12 14:52 UTC, djelinek approved these changes

2021-02-12 17:03 UTC, bfitzpat approved these changes

2021-02-12 17:04 UTC, merged