FUSETOOLS-3519: Fix UI Test 'DataTransformationDeploymentTest' and convert it into master branch
jbosstools/jbosstools-fuse pull request #1725
Opened 2021-10-06 10:47 UTC by pospisilf

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

2021-10-11 20:40 UTC, pospisilf commented
Should be improved.

2021-10-15 08:23 UTC, pospisilf commented
rebased

2021-11-07 21:39 UTC, pospisilf commented
testPR

2021-11-10 10:52 UTC, apupier requested changes

2021-11-10 10:52 UTC, apupier commented on uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DataTransformationDefaultTest.java
> +//		new WaitUntil(new ShellIsActive("New Fuse Transformation"), TimePeriod.getCustom(600));
commented out lien can be removed

2021-11-10 12:29 UTC, pospisilf commented on uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DataTransformationDefaultTest.java
> +//		new WaitUntil(new ShellIsActive("New Fuse Transformation"), TimePeriod.getCustom(600));
Fixed, thanks for noticing.

2021-12-02 16:26 UTC, pospisilf commented
Skipping tests affected by opened JIRA issues can be handled better. Will be redone.

2021-12-02 16:26 UTC, closed without merging